// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skxjfqxpigouckadshbw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNreGpmcXhwaWdvdWNrYWRzaGJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMTYzODcsImV4cCI6MjA2ODc5MjM4N30.77lJwU-eKRzygntBbt_ZQb0beUb6a07rThLGN26PB9M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});